/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minisql;

import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Admin
 */
public class Compilador extends javax.swing.JFrame {

    /**
     * Creates new form Compilador
     */
    LinkedList ColaAnalisis;
    TokenAnalisis Actual;
    int Sentencia = 1;
    boolean ErrorSintactico = false;

    public Compilador() {
        ColaAnalisis = new LinkedList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPath = new javax.swing.JLabel();
        btnPath = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaResultado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaResultado1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Compilador MiniSQL");

        lblPath.setText("Archivo...");

        btnPath.setText("Seleccionar");
        btnPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPathActionPerformed(evt);
            }
        });

        jtaResultado.setColumns(1);
        jtaResultado.setLineWrap(true);
        jtaResultado.setRows(5);
        jScrollPane1.setViewportView(jtaResultado);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Análisis Lexico");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Análisis Sintáctico");

        jtaResultado1.setColumns(1);
        jtaResultado1.setLineWrap(true);
        jtaResultado1.setRows(5);
        jScrollPane2.setViewportView(jtaResultado1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(306, 306, 306)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)))
                        .addGap(0, 414, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPath)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPath)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPath)
                    .addComponent(lblPath))
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblPath.getAccessibleContext().setAccessibleName("lblPath");
        btnPath.getAccessibleContext().setAccessibleName("btnPath");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPathActionPerformed
        JFileChooser Explorador = new JFileChooser();
        Explorador.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter Filtro = new FileNameExtensionFilter("Archivos SQL", "sql");
        Explorador.setFileFilter(Filtro);

        Explorador.showOpenDialog(this);
        File ArchivoSQL = Explorador.getSelectedFile();

        String path = ArchivoSQL.getAbsolutePath();
        String Path = path.substring(0, path.length() - 4);

        String PathOut = Path + ".out";

        try {
            AnalizarTokens(ArchivoSQL, PathOut);
        } catch (Exception ex) {
            Logger.getLogger(Compilador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPathActionPerformed

    // Método que escribe el archivo .out y escribe en pantalla el analisis del archivo.
    private void AnalizarTokens(File ArchivoSQL, String PathOut) throws Exception {
        if (ArchivoSQL == null) {
            lblPath.setText("Debes seleccionar un archivo SQL válido");
        } else {
            lblPath.setText(ArchivoSQL.getPath());
        }

        try {
            Reader reader = new BufferedReader(new FileReader(ArchivoSQL.getPath()));
            Lexer lexer = new Lexer(reader);

            List Lista = new List();

            Token token;
            token = lexer.yylex();
            
            // Variables para analizar si se debe analizar la expresion Sintacticamente
            boolean flagError = false;
            LinkedList ColaTemp = new LinkedList();
            

            while (token != null) {
                TokenAnalisis tok;

                switch (token) {
                    case ERROR:
                        jtaResultado.append("Linea " + (lexer.line + 1) + ". Error: Caracter no Reconocido:\t" + lexer.lexeme
                                + "\t{Columna Inicial:" + lexer.columni + " Columna Final: " + lexer.columnf + "}\n");
                        Lista.add("Linea " + (lexer.line + 1) + ". Error: Caracter no Reconocido:\t" + lexer.lexeme
                                + "\t{Columna Inicial:" + lexer.columni + " Columna Final: " + lexer.columnf + "}\n");
                        flagError = true;
                        break;

                    case IDENTIFICADOR:
                        // Si el identificador tiene mas de 31 caracteres lanza error.
                        if (lexer.lexeme.length() > 31) {
                            char[] cidentificador = lexer.lexeme.toCharArray();
                            String identificador = "";

                            for (int i = 0; i < 31; i++) {
                                identificador += Character.toString(cidentificador[i]);
                            }

                            jtaResultado.append("Linea " + (lexer.line + 1) + ". Error: " + "Identificador.lenght" + ":\t" + identificador
                                    + "\t{Columna Inicial:" + lexer.columni + " Columna Final: " + lexer.columnf + "}\n");
                            Lista.add("Linea " + (lexer.line + 1) + ". Error: " + "Identificador.lenght" + ":\t" + identificador
                                    + "\t{Columna Inicial:" + lexer.columni + " Columna Final: " + lexer.columnf + "}\n");

                            flagError = true;

                        } else {
                            jtaResultado.append("Linea " + (lexer.line + 1) + ". Token: " + token + ":\t" + lexer.lexeme
                                    + "\t{Columna Inicial:" + lexer.columni + " Columna Final: " + lexer.columnf + "}\n");
                            Lista.add("Linea " + (lexer.line + 1) + ". Token: " + token + ":\t" + lexer.lexeme
                                    + "\t{Columna Inicial:" + lexer.columni + " Columna Final: " + lexer.columnf + "}\n");

                            tok = new TokenAnalisis(token, lexer.lexeme, lexer.line + 1, lexer.columni, lexer.columnf);
                            ColaTemp.offer(tok);
                        }
                        break;

                    case ERROR_CADENA:
                        jtaResultado.append("Linea " + (lexer.line + 1) + ". Error: String sin Cierre :\t\t" + lexer.lexeme
                                + "\t{Columna Inicial:" + lexer.columni + " Columna Final: " + lexer.columnf + "}\n");
                        Lista.add("Linea " + (lexer.line + 1) + ". Error: String sin Cierre :\t\t" + lexer.lexeme
                                + "\t{Columna Inicial:" + lexer.columni + " Columna Final: " + lexer.columnf + "}\n");
                        
                        flagError = true;
                        break;

                    case ERROR_COMENTARIO:

                        char[] letras = lexer.lexeme.trim().toCharArray();

                        if (!(letras[0] == '/' && letras[1] == '*' && letras[letras.length - 2] == '*' && letras[letras.length - 1] == '/')) {
                            jtaResultado.append("Linea " + (lexer.line + 1) + ". Error: Comentario sin Terminar :\t" + lexer.lexeme
                                    + "\t{Columna Inicial:" + lexer.columni + " Columna Final: " + lexer.columnf + "}\n");
                            Lista.add("Linea " + (lexer.line + 1) + ". Error: Comentario sin Terminar :\t" + lexer.lexeme
                                    + "\t{Columna Inicial:" + lexer.columni + " Columna Final: " + lexer.columnf + "}\n");
                            flagError = true;
                        }
                        break;

                    default:
                        jtaResultado.append("Linea " + (lexer.line + 1) + ". Token: " + token + ":\t\t" + lexer.lexeme
                                + "\t{Columna Inicial:" + lexer.columni + " Columna Final: " + lexer.columnf + "}\n");
                        Lista.add("Linea " + (lexer.line + 1) + ". Token: " + token + ":\t\t" + lexer.lexeme
                                + "\t{Columna Inicial:" + lexer.columni + " Columna Final: " + lexer.columnf + "}\n");

                        tok = new TokenAnalisis(token, lexer.lexeme, lexer.line + 1, lexer.columni, lexer.columnf);
                        ColaTemp.offer(tok);
                        break;
                }

                token = lexer.yylex();
                
                // Si llegamos al final de la sentencia...
                if (token == Token.PYC || token == Token.GO)
                {
                    // ... Y no hubo ningún error lexico ...
                    if (!flagError)
                    {
                        // ... Se agrega el token final a la cola
                        tok = new TokenAnalisis(token, lexer.lexeme, lexer.line + 1, lexer.columni, lexer.columnf);
                        ColaTemp.offer(tok);

                        // Se avanza una posicion más... 
                        token = lexer.yylex();
                        // ... Si hay otro final es porque debería de haber un GO despues de un ;
                        if (token == Token.GO)
                        {
                            // Se agrega el otro final a la cola de analisis temporal
                            tok = new TokenAnalisis(token, lexer.lexeme, lexer.line + 1, lexer.columni, lexer.columnf);
                            ColaTemp.offer(tok);
                            token = lexer.yylex();
                        }
                        
                        // Como no hubo error se agrega toda la sentencia guardada en ColaTemp a la ColaAnalisis
                        while(ColaTemp.peek() != null)
                            ColaAnalisis.offer(ColaTemp.poll());
                    }
                    // ... Si se encontró un error en el proceso se descarta todo lo guardado en la ColaTemp
                    else
                    {
                        token = lexer.yylex();
                        // Se busca si venía el GO después del PYC
                        if (token == Token.GO)
                            token = lexer.yylex();
                        
                        // Se descarta todo
                        while(ColaTemp.peek() != null)
                            ColaTemp.poll();
                        
                        // Se resetea la flagError
                        flagError = false;
                    }
                }

            }

            // FINAL DEL ANALISIS LEXICO
            jtaResultado.append("FIN DE LECTURA");
            Lista.add("FIN DE LECTURA");

            // ESCRITURA DEL ARCHIVO .OUT
            EscrituraOutLexico(PathOut, Lista);
            ArchivoPrevioAnalisisLexico(ColaAnalisis);
            AnalisisSintactico();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Compilador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Compilador.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void EscrituraOutLexico(String PathOut, List Lista) throws IOException
    {
        // Escritor del archivo de salida.
        File ArchivoOut = new File(PathOut);
        FileWriter writer = new FileWriter(ArchivoOut);
        PrintWriter pw = new PrintWriter(ArchivoOut);

        pw.write(Lista.getItem(0));

        int cont = 1;

        while (!Lista.getItem(cont).equals("FIN DE LECTURA")) {
            pw.append(Lista.getItem(cont));
            cont++;
        }

        pw.append("FIN DE LECTURA");

        pw.close();
        writer.close();
    }

    private void ArchivoPrevioAnalisisLexico(LinkedList ColaAnalisis) throws IOException
    {
        String PathArchivo = "C:\\Users\\Admin\\Desktop\\PrevioSintactico.txt";
        // Escritor del archivo de salida.
        File ArchivoOut = new File(PathArchivo);
        FileWriter writer = new FileWriter(ArchivoOut);
        PrintWriter pw = new PrintWriter(ArchivoOut);

        int linea = 1;
        int columnai = 0;
        int columnaf = 0;
        String Linea = "";
                
        TokenAnalisis Tok;

        while (ColaAnalisis.peek() != null) 
        {
            Tok = (TokenAnalisis) ColaAnalisis.poll();
            columnai = Tok.columnai;
            
            if (Tok.linea == linea)
            {
                while (columnai - columnaf > 1)
                {
                    Linea += ' ';
                    columnaf++;
                }
                Linea += Tok.produccion;
                
                columnaf = Tok.columnaf;
            }
            else
            {
                Linea += "\n";
                pw.append(Linea);
                linea++;
                
                while(Tok.linea != linea)
                {
                    Linea = "";
                    Linea += "\n";
                    pw.append(Linea);
                    linea++;
                }
                
                Linea = "";
                Linea += Tok.produccion;
                
                columnaf = Tok.columnaf;
            }
        }
        
        pw.append(Linea);
        
        pw.close();
        writer.close();
    }
    
    private void AnalisisSintactico () throws IOException, Exception
    {
        String PathArchivo = "C:\\Users\\Admin\\Desktop\\PrevioSintactico.txt";
        
        LinkedList<String> ErroresSintacticos = null;
        
        String Texto = new String(Files.readAllBytes(Paths.get(PathArchivo)));
        Sintax s = new Sintax(new minisql.LexerCup(new StringReader(Texto)));
        
        s.parse();
        
        //Se agrega la lista de errores sintacticos
        ErroresSintacticos = s.Errores;
        
        while (ErroresSintacticos.peek() != null)
        {
            jtaResultado1.append(ErroresSintacticos.removeFirst());
            jtaResultado1.append("\n");
        }
        
        String TextoImpreso = jtaResultado1.getText();
        
        if(TextoImpreso.length() == 0)
            jtaResultado1.append("ANÁLISIS SINTÁCTICO FINALIZADO");
        else
            jtaResultado1.append("\nANÁLISIS SINTÁCTICO FINALIZADO");
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compilador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jtaResultado;
    private javax.swing.JTextArea jtaResultado1;
    private javax.swing.JLabel lblPath;
    // End of variables declaration//GEN-END:variables
}
